-- K-water 표준도메인사전 시드 데이터
-- 원본: 표준 데이터 조회_K-water데이터표준_도메인사전.xlsx
-- 생성일: 2026-03-18

DELETE FROM std_domn_dict;

INSERT INTO std_domn_dict (domn_grp_nm, domn_nm, domn_lgc_nm, data_ty, data_len, deci_point, psnl_info_yn, enc_yn, scrbl, dc) VALUES
('수량', '1인당1일급수량', '1인당1일급수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_1인당1일급수량'),
('수량', 'BOD측정값', 'BOD측정값DEC14,4', 'NUMERIC', 14, 4, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_BOD측정값'),
('수량', 'COD측정값', 'COD측정값DEC14,4', 'NUMERIC', 14, 4, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_COD측정값'),
('분류', 'GFP상태코드', 'GFP상태코드VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_GFP상태코드'),
('수량', 'GFP운전시간값', 'GFP운전시간값DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_GFP운전시간값'),
('번호', 'ID', 'IDVC100', 'VARCHAR', 100, NULL, 'N', 'N', NULL, 'ID 100 자리'),
('번호', 'ID', 'IDVC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_ID'),
('번호', 'ID', 'IDVC200', 'VARCHAR', 200, NULL, 'N', 'N', NULL, '200자리 ID값'),
('번호', 'ID', 'IDVC300', 'VARCHAR', 300, NULL, 'N', 'N', NULL, '300자리 ID값'),
('번호', 'ID', 'IDVC40', 'VARCHAR', 40, NULL, 'N', 'N', NULL, '로그를 저장하는 ID값으로 기존 도메인 20자리를 초과한 40자 형태로 표현된다.'),
('기타', 'ID', 'IDVC50', 'VARCHAR', 50, NULL, 'N', 'N', NULL, 'ID 도메인 vc 50'),
('주소', 'IP', 'IPVC50', 'VARCHAR', 50, NULL, 'N', 'N', NULL, 'test'),
('주소', 'MAC주소', 'MAC주소VC50', 'VARCHAR', 50, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_MAC주소'),
('비율', 'PH', 'PHDEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_PH'),
('주소', 'URL', 'URLVC1000', 'VARCHAR', 1000, NULL, 'N', 'N', NULL, '환경산업기술원에서 사용하는 홈페이지 URL'),
('주소', 'URL', 'URLVC255', 'VARCHAR', 255, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_URL'),
('수량', 'U성분풍속', 'U성분풍속DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_U성분풍속'),
('수량', 'V성분풍속', 'V성분풍속DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_V성분풍속'),
('번호', 'WINS표준코드', 'WINS표준코드VC10', 'VARCHAR', 10, NULL, 'N', 'N', NULL, '농어촌공사 연계 WINS 표준코드'),
('번호', 'X좌표', 'X좌표DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '지도상에서 x축위치'),
('번호', 'Y좌표', 'Y좌표DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_Y좌표'),
('번호', 'Z좌표', 'Z좌표DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_Z좌표'),
('금액', '가격', '가격DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_가격'),
('금액', '가격', '가격DEC15', 'NUMERIC', 15, NULL, NULL, NULL, NULL, '물건이 지니고 있는 가치를 돈으로 나타낸 것'),
('수량', '가능량', '가능량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_가능량'),
('비율', '가동률', '가동률DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_가동률'),
('기타', '가뭄정보관리관할기관코드', '가뭄정보관리관할기관코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '개별코드'),
('기타', '가뭄정보관리급수체계코드', '가뭄정보관리급수체계코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '개별코드'),
('기타', '가뭄정보관리배수지코드', '가뭄정보관리배수지코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '개별코드'),
('기타', '가뭄정보관리사용자코드', '가뭄정보관리사용자코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '(개별코드 신청)
가뭄 정보 시스템을 이용하거나 급수와 관련된 대상(개인, 기관, 산업체 등)을 식별하기 위한 고유 식별 코드'),
('기타', '가뭄정보관리산업단지코드', '가뭄정보관리산업단지코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '개별코드'),
('기타', '가뭄정보관리수원코드', '가뭄정보관리수원코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '개별코드'),
('기타', '가뭄정보관리정수장코드', '가뭄정보관리정수장코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '개별코드'),
('기타', '가뭄정보관리하수처리시설코드', '가뭄정보관리하수처리시설코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '개별코드'),
('금액', '가산금', '가산금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_가산금'),
('비율', '가중치', '가중치DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_가중치'),
('비율', '가중치', '가중치DEC6,3', 'NUMERIC', 6, 3, 'N', 'N', NULL, '加重値.평균치를 산출할 때 각 개별치에 부여되는 중요도.'),
('수량', '각도', '각도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_각도'),
('금액', '간접노무비', '간접노무비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_간접노무비'),
('금액', '간접비', '간접비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_간접비'),
('금액', '간접재료비', '간접재료비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_간접재료비'),
('수량', '갈수량', '갈수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_갈수량'),
('수량', '갈수위', '갈수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_갈수위'),
('금액', '감면액', '감면액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_감면액'),
('금액', '감면잔액', '감면잔액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_감면잔액'),
('기타', '값', '값CH1', 'CHAR', 1, NULL, 'N', 'N', NULL, '1 : 각자대표 
2 : 공동대표 
3 : 법인상호대표 
NULL : (단독대표 OR 업체정보 미확인자)'),
('기타', '값', '값DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_값'),
('수량', '값', '값DEC10,3', 'NUMERIC', 10, 3, 'N', 'N', NULL, '유입 BOD 값
유입 COD 값
유입 SS 값
유입 총질소 값
유입 총인 값 등의 환경시설에서 사용하는 측정값에 사용하는 도메인'),
('기타', '값', '값VC10', 'VARCHAR', 10, NULL, 'N', 'N', NULL, '1. 사고파는 물건에 일정하게 매겨진 액수 
2. 물건을 사고팔 때 주고받는 돈 
3. 어떤 사물의 중요성이나 의의 
4. 노력이나 희생에 따른 대가 
5. 어떤 것에 합당한 노릇이나 구실 
6. (수학) 하나의 글자나 식이 취하는 수. 또는 그런 수치'),
('기타', '값', '값VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_값'),
('기타', '값', '값VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_값'),
('기타', '값', '값VC30', 'VARCHAR', 30, NULL, 'N', 'N', NULL, '조달청 차세대 나라장터 연계 전자문서 중 회원정보의 업체 면허등록번호값'),
('기타', '값', '값VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_값'),
('수량', '강설량', '강설량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_강설량'),
('수량', '강수량', '강수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_강수량'),
('수량', '강수량', '강수량DEC15,4', 'NUMERIC', 15, 4, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_강수량'),
('수량', '강우량', '강우량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_강우량'),
('비율', '개도', '개도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_개도'),
('금액', '개선비', '개선비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_개선비'),
('수량', '개월수', '개월수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_개월수'),
('수량', '개월수', '개월수DEC6,2', 'NUMERIC', 6, 2, 'N', 'N', NULL, '사업의 개월수'),
('번호', '개인식별번호', '개인식별번호VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_개인식별번호'),
('수량', '거리', '거리DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_거리'),
('분류', '건강증진프로그램상태구분코드', '건강증진프로그램상태구분코드VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '건강증진프로그램상태구분코드'),
('분류', '건강증진프로그램종류구분코드', '건강증진프로그램종류구분코드VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '건강증진프로그램종류구분코드'),
('번호', '건물번호', '건물번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, '건물등(둘 이상의 건물등이 현실적으로 하나의 집단을 형성하고 있는 경우에는 그 건물등의 전체)마다 부여된 번호'),
('번호', '건물본번', '건물본번DEC5', 'NUMERIC', 5, NULL, NULL, NULL, NULL, '건물마다에 매긴 번호의 붙임표(-) 앞에 오는 주된 번호'),
('번호', '건물부번', '건물부번DEC5', 'NUMERIC', 5, NULL, NULL, NULL, NULL, '건물마다에 매긴 번호의 붙임표(-) 뒤에 오는 가지 번호'),
('수량', '건수', '건수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_건수'),
('금액', '검사수수료', '검사수수료DEC22', 'NUMERIC', 22, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_검사수수료'),
('텍스트', '결과', '결과VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_결과'),
('텍스트', '결과', '결과VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_결과'),
('텍스트', '결과', '결과VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_결과'),
('분류', '결과파일ID', '결과파일IDDEC20', 'NUMERIC', 20, NULL, 'N', 'N', NULL, 'ID 번호'),
('금액', '결산금액', '결산금액DEC22', 'NUMERIC', 22, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_결산금액'),
('번호', '결재기안내역번호', '결재기안내역번호VC10', 'VARCHAR', 10, NULL, 'N', 'N', NULL, '일련번호(10)'),
('번호', '경도', '경도DEC13,10', 'NUMERIC', 13, 10, NULL, NULL, NULL, '지구 위의 위치를 나타내는 좌표축 중에서 세로로 된 것. 한 지점의 경도는 그 지점을 지나는 자오선과 런던의 그리니치 천문대를 지나는 본초 자오선이 이루는 각도'),
('번호', '경도', '경도VC15', 'VARCHAR', 15, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_경도'),
('번호', '경도', '경도VC20', 'VARCHAR', 20, NULL, 'N', 'N', NULL, '좌표상 경도의 값이 기존 도메인 15자리를 초과한 20자 형태로 표현된다.'),
('주소', '경로', '경로VC255', 'VARCHAR', 255, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_경로'),
('금액', '경비', '경비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_경비'),
('번호', '경위도', '경위도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_경위도'),
('수량', '계수', '계수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_계수'),
('수량', '계수', '계수DEC10,3', 'NUMERIC', 10, 3, 'N', 'N', NULL, '하나의 수량을 여러 양의 다른 함수로 나타내는 관계식에서 숫자를 기호 문자에 대하여 이름'),
('수량', '계수', '계수DEC13,10', 'NUMERIC', 13, 10, 'N', 'N', NULL, '어떤 금액의 현재 가치를 산출 하는 계수'),
('금액', '계약금액', '계약금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_계약금액'),
('수량', '계약기간', '계약기간DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_계약기간'),
('금액', '계약보증금', '계약보증금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_계약보증금'),
('수량', '계약수량', '계약수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_계약수량'),
('번호', '계좌번호', '계좌번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_계좌번호'),
('번호', '계좌번호', '계좌번호VC50', 'VARCHAR', 50, NULL, 'N', 'N', NULL, '조달청의 가상계좌번호'),
('번호', '계측기번호', '계측기번호VC7', 'VARCHAR', 7, NULL, NULL, NULL, NULL, '계측기유형(3) + 번호(4)'),
('날짜', '계측시각', '계측시각VC12', 'VARCHAR', 12, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_계측시각'),
('수량', '계획홍수위', '계획홍수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_계획홍수위'),
('수량', '고수위', '고수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_고수위'),
('번호', '고유번호', '고유번호DEC20', 'NUMERIC', 20, NULL, 'N', 'N', NULL, '고유번호'),
('번호', '고유번호', '고유번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_고유번호'),
('번호', '고재처리번호', '고재처리번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+시퀀스일련번호(6)'),
('번호', '고지서순번', '고지서순번VC15', 'VARCHAR', 15, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_고지서순번'),
('기타', '공간데이터정보', '공간데이터정보GEO', 'GEOMETRY', NULL, NULL, 'N', 'N', NULL, '시설, 지점, 구역 등의 물리적 대상에 대한 위치, 형상, 공간적 속성 등을 디지털 좌표 체계 기반으로 표현한 정보'),
('번호', '공고번호', '공고번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_공고번호'),
('금액', '공급가액', '공급가액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_공급가액'),
('수량', '공급량', '공급량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_공급량'),
('기타', '공급품목구분코드', '공급품목구분코드VC6', 'VARCHAR', 6, NULL, 'N', 'N', NULL, '공급품목구분코드 도메인'),
('금액', '공사금액', '공사금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_공사금액'),
('번호', '공사번호', '공사번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+시퀀스일련번호(6)'),
('금액', '공사비', '공사비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_공사비'),
('금액', '공정비용', '공정비용DEC22', 'NUMERIC', 22, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_공정비용'),
('금액', '공제금액', '공제금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_공제금액'),
('수량', '관경', '관경DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_관경'),
('금액', '관리비', '관리비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_관리비'),
('차례', '관저고', '관저고DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_관저고'),
('수량', '구경', '구경DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_구경'),
('비율', '구배', '구배DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_구배'),
('텍스트', '구분자', '구분자VC1', 'VARCHAR', 1, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_구분자'),
('기타', '구분자', '구분자VC3', 'VARCHAR', 3, NULL, 'N', 'N', NULL, '구분자 도메인 항목'),
('번호', '구우편번호', '구우편번호CH6', 'CHAR', 6, NULL, NULL, NULL, NULL, '앞 세 자리는 특별시, 광역시, 시도를 나타내고, 뒤에 세 자리는 전국 집배원들의 배달구역 번호를 나타낸 과거 지번주소에 부여된 우편번호'),
('번호', '국제횡축메르카토르X축', '국제횡축메르카토르X축DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_국제횡축메르카토르X축'),
('번호', '국제횡축메르카토르Y축', '국제횡축메르카토르Y축DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_국제횡축메르카토르Y축'),
('수량', '근로자수', '근로자수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '근로자수DEC'),
('금액', '금액', '금액DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '길이 없는 금액 도메인'),
('금액', '금액', '금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_금액'),
('금액', '금액', '금액DEC15', 'NUMERIC', 15, NULL, NULL, NULL, NULL, '돈의 액수'),
('금액', '금액', '금액DEC18,2', 'NUMERIC', 18, 2, 'N', 'N', NULL, '환율에 의한 원화 금액 계산으로 소숫점 금액으로 표현 필요'),
('금액', '금액', '금액DEC18,3', 'NUMERIC', 18, 3, 'N', 'N', NULL, '가치평가 관련하여 AS-IS 시스템에서  산출된 금액이 소숫점 3자리로 구현되어 있습니다. 현재 등록된 도메인이 소숫점 3자리가 존재 하지 않습니다. 등록된 도메인 중 가장 근접한 자릿수가 18,2가 있으나 이 도메인을 사용하면 산출 금액이 왜곡 될 수 있습니다.'),
('금액', '금액', '금액DEC19', 'NUMERIC', 19, NULL, 'N', 'N', NULL, '금액 도메인 Num19'),
('금액', '금액', '금액DEC22,2', 'NUMERIC', 22, 2, NULL, NULL, NULL, '돈의 액수'),
('수량', '기간', '기간DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_기간'),
('날짜', '기간', '기간VC100', 'VARCHAR', 100, NULL, 'N', 'N', NULL, 'from 날짜와 to날짜를 입력'),
('수량', '기압', '기압DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_기압'),
('수량', '기온', '기온DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_기온'),
('금액', '기준금액', '기준금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_기준금액'),
('날짜', '기준년', '기준년VC4', 'VARCHAR', 4, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_기준년'),
('금액', '기타금액', '기타금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_기타금액'),
('수량', '길이', '길이DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_길이'),
('수량', '깊이', '깊이DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_깊이'),
('날짜', '날짜일자', '날짜일자TMP', 'TIMESTAMP', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_날짜일자'),
('금액', '납부금액', '납부금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_납부금액'),
('텍스트', '내역', '내역VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_내역'),
('텍스트', '내역', '내역VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_내역'),
('텍스트', '내역', '내역VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_내역'),
('텍스트', '내역', '내역VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_내역'),
('텍스트', '내용', '내용BL', 'BLOB', NULL, NULL, 'N', 'N', NULL, '바이너리 문서 파일'),
('텍스트', '내용', '내용CL', 'CLOB', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_내용'),
('텍스트', '내용', '내용NCL', 'NCLOB', NULL, NULL, 'N', 'N', NULL, '다양한 문자셋을 지원하는 데이터타입'),
('텍스트', '내용', '내용VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_내용'),
('텍스트', '내용', '내용VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_내용'),
('텍스트', '내용', '내용VC2000', 'VARCHAR', 2000, NULL, NULL, NULL, NULL, '문자형 데이터를 정의한 것'),
('텍스트', '내용', '내용VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_내용'),
('텍스트', '내용', '내용VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_내용'),
('수량', '너비', '너비DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_너비'),
('날짜', '년도', '년도VC4', 'VARCHAR', 4, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_년도'),
('수량', '년수', '년수DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '년수DEC'),
('날짜', '년월', '년월VC6', 'VARCHAR', 6, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_년월'),
('금액', '노무비', '노무비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_노무비'),
('비율', '농도', '농도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_농도'),
('수량', '높이', '높이DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_높이'),
('수량', '누수량', '누수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_누수량'),
('분류', '다운로드항목구분코드', '다운로드항목구분코드VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_다운로드항목구분코드'),
('금액', '단가', '단가DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_단가'),
('금액', '단가', '단가DEC16,3', 'NUMERIC', 16, 3, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_단가'),
('금액', '대금', '대금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_대금'),
('금액', '대상금액', '대상금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_대상금액'),
('명', '도로명', '도로명VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_도로명'),
('주소', '도로명주소', '도로명주소VC200', 'VARCHAR', 200, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_도로명주소'),
('금액', '도시계획세', '도시계획세DEC15', 'NUMERIC', 15, NULL, 'N', 'N', NULL, '[법률] 지방세의 하나. 도시 계획 사업비에 충당하기 위하여 도시 계획 구역 안에 있는 토지나 가옥의 소유자에게 부과하는 목적세.'),
('수량', '두께', '두께DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_두께'),
('수량', '둘레', '둘레DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_둘레'),
('차례', '등급', '등급DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_등급'),
('수량', '량', '량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_량'),
('수량', '량', '량DEC10,3', 'NUMERIC', 10, 3, 'N', 'N', NULL, '량 NUMERIC(10,3)'),
('수량', '량', '량DEC15,4', 'NUMERIC', 15, 4, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_량'),
('수량', '량', '량DEC18,2', 'NUMERIC', 18, 2, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_량'),
('차례', '레벨', '레벨DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_레벨'),
('차례', '레벨', '레벨VC1', 'VARCHAR', 1, NULL, 'N', 'N', NULL, 'KRM의 위험, 설비 등의 수준을 레벨로 관리하기위하여 영문 한자리로 표기한 정보이다.'),
('수량', '레코드건수', '레코드건수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_레코드건수'),
('번호', '로우번호', '로우번호DEC20', 'NUMERIC', 20, NULL, 'N', 'N', NULL, '행번호'),
('텍스트', '리스트', '리스트VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_리스트'),
('텍스트', '리스트', '리스트VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_리스트'),
('텍스트', '리스트', '리스트VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_리스트'),
('텍스트', '리스트', '리스트VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_리스트'),
('수량', '만수위', '만수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_만수위'),
('수량', '만점', '만점DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_만점'),
('금액', '매출액', '매출액DEC22', 'NUMERIC', 22, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_매출액'),
('텍스트', '메뉴경로', '메뉴경로VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_메뉴경로'),
('텍스트', '메뉴사용여부', '메뉴사용여부CH1', 'CHAR', 1, NULL, 'N', 'N', NULL, '메뉴사용여부'),
('번호', '메르카토르X축', '메르카토르X축DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_메르카토르X축'),
('번호', '메르카토르Y축', '메르카토르Y축DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_메르카토르Y축'),
('수량', '메모리사용량', '메모리사용량VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_메모리사용량'),
('수량', '면적', '면적DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_면적'),
('명', '명', '명VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, NULL),
('명', '명', '명VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, NULL),
('명', '명', '명VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, NULL),
('명', '명', '명VC150', 'VARCHAR', 150, NULL, 'N', 'N', NULL, '名 사람의 이름 사물의 명'),
('명', '명', '명VC200', 'VARCHAR', 200, NULL, 'N', 'N', NULL, '명VC200'),
('명', '명', '명VC300', 'VARCHAR', 300, NULL, NULL, NULL, NULL, '다른 것과 구별하기 위하여 사물, 단체, 현상 따위에 붙여서 부르는 말, ''이름''의 뜻을 나타내는 말'),
('명', '명', '명VC40', 'VARCHAR', 40, NULL, NULL, NULL, NULL, '다른 것과 구별하기 위하여 사물, 단체, 현상 따위에 붙여서 부르는 말, ''이름''의 뜻을 나타내는 말'),
('명', '명', '명VC5', 'VARCHAR', 5, NULL, NULL, NULL, NULL, '다른 것과 구별하기 위하여 사물, 단체, 현상 따위에 붙여서 부르는 말, ''이름''의 뜻을 나타내는 말'),
('명', '명', '명VC80', 'VARCHAR', 80, NULL, NULL, NULL, NULL, '다른 것과 구별하기 위하여 사물, 단체, 현상 따위에 붙여서 부르는 말, ''이름''의 뜻을 나타내는 말'),
('날짜', '모의시각', '모의시각VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_모의시각');

INSERT INTO std_domn_dict (domn_grp_nm, domn_nm, domn_lgc_nm, data_ty, data_len, deci_point, psnl_info_yn, enc_yn, scrbl, dc) VALUES
('수량', '무게', '무게DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_무게'),
('수량', '무게', '무게DEC18,4', 'NUMERIC', 18, 4, 'N', 'N', NULL, '중력에 의해 객체가 지구 중심으로 끌리는 힘'),
('수량', '무수량', '무수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_무수량'),
('번호', '문서번호', '문서번호VC50', 'VARCHAR', 50, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_문서번호'),
('수량', '물량', '물량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_물량'),
('금액', '미납금', '미납금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_미납금'),
('비율', '밀도', '밀도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_밀도'),
('수량', '반경', '반경DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_반경'),
('금액', '발급수수료', '발급수수료DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_발급수수료'),
('날짜', '발생시각', '발생시각VC12', 'VARCHAR', 12, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_발생시각'),
('날짜', '발표시각', '발표시각VC12', 'VARCHAR', 12, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_발표시각'),
('수량', '방류가능량', '방류가능량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_방류가능량'),
('수량', '방류량', '방류량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_방류량'),
('수량', '방수위', '방수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_방수위'),
('수량', '방향각', '방향각DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_방향각'),
('비율', '배율', '배율DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_배율'),
('수량', '배점', '배점DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_배점'),
('수량', '배점', '배점DEC10,3', 'NUMERIC', 10, 3, 'N', 'N', NULL, '점수를 각가 나누어 배정함. 또는 그렇게 하여 정해진 점수'),
('수량', '배출량', '배출량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_배출량'),
('번호', '버전', '버전VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_버전'),
('번호', '번호', '번호CH13', 'CHAR', 13, NULL, NULL, NULL, NULL, '차례를 나타내거나 식별하기위해붙이는 숫자나 문자를 고정된 길이로 정의한 것'),
('번호', '번호', '번호CH7', 'CHAR', 7, NULL, NULL, NULL, NULL, '차례를 나타내거나 식별하기위해붙이는 숫자나 문자를 고정된 길이로 정의한 것'),
('번호', '번호', '번호DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_번호'),
('번호', '번호', '번호VC10', 'VARCHAR', 10, NULL, 'N', 'N', NULL, '차례를 나타내거나 식별하기위해붙이는 숫자나 문자를 고정된 길이로 정의한 것'),
('번호', '번호', '번호VC100', 'VARCHAR', 100, NULL, 'N', 'N', NULL, '조달청 조달요청서번호'),
('번호', '번호', '번호VC13', 'VARCHAR', 13, NULL, NULL, NULL, NULL, '차례를 나타내거나 식별하기 위해 붙이는 숫자나 문자를 고정되지 않은 길이로 정의한 것'),
('번호', '번호', '번호VC16', 'VARCHAR', 16, NULL, 'N', 'N', NULL, '차례를 나타내거나 식별하기위해붙이는 숫자나 문자를 고정된 길이로 정의한 것'),
('번호', '번호', '번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_번호'),
('번호', '번호', '번호VC24', 'VARCHAR', 24, NULL, NULL, NULL, NULL, '차례를 나타내거나 식별하기 위해 붙이는 숫자나 문자를 고정되지 않은 길이로 정의한 것'),
('번호', '번호', '번호VC25', 'VARCHAR', 25, NULL, NULL, NULL, NULL, '차례를 나타내거나 식별하기 위해 붙이는 숫자나 문자를 고정되지 않은 길이로 정의한 것'),
('수량', '번호', '번호VC30', 'VARCHAR', 30, NULL, 'N', 'N', NULL, '차례를 나타내거나 식별하기위해붙이는 숫자나 문자를 고정된 길이로 정의한 것'),
('번호', '번호', '번호VC50', 'VARCHAR', 50, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_번호'),
('번호', '번호', '번호VC60', 'VARCHAR', 60, NULL, 'N', 'N', NULL, '조달청 차세대 나라장터 연계 전자문서 중 신용평가정보의 채권번호(60자)'),
('번호', '번호', '번호VC9', 'VARCHAR', 9, NULL, NULL, NULL, NULL, '차례를 나타내거나 식별하기 위해 붙이는 숫자나 문자를 고정되지 않은 길이로 정의한 것'),
('번호', '법인등록번호', '법인등록번호VC14', 'VARCHAR', 14, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_법인등록번호'),
('금액', '변경금액', '변경금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_변경금액'),
('텍스트', '변경사유', '변경사유VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_변경사유'),
('텍스트', '변경사유', '변경사유VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_변경사유'),
('텍스트', '변경사유', '변경사유VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_변경사유'),
('텍스트', '변경사유', '변경사유VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_변경사유'),
('명', '별칭', '별칭VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_별칭'),
('분류', '보건설정ID', '보건설정IDVC4', 'VARCHAR', 4, NULL, 'N', 'N', NULL, '보건설정ID'),
('분류', '보건조직도설정ID', '보건조직도설정IDVC4', 'VARCHAR', 4, NULL, 'N', 'N', NULL, '보건조직도설정ID'),
('금액', '보상금', '보상금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_보상금'),
('금액', '보증금', '보증금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_보증금'),
('금액', '부가가치세', '부가가치세DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_부가가치세'),
('금액', '부담금', '부담금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_부담금'),
('수량', '부수', '부수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_부수'),
('금액', '분담금', '분담금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_분담금'),
('분류', '분야코드', '분야코드VC1', 'VARCHAR', 1, NULL, 'N', 'N', NULL, '분야코드값'),
('분류', '분야코드', '분야코드VC3', 'VARCHAR', 3, NULL, 'N', 'N', NULL, '업체의 사업 및 자격 분야를 구분하는 코드'),
('금액', '비', '비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비'),
('금액', '비', '비DEC14', 'NUMERIC', 14, NULL, 'N', 'N', NULL, '금액, 비용 NUMBER(14) 도메인'),
('텍스트', '비고', '비고VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비고'),
('텍스트', '비고', '비고VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비고'),
('텍스트', '비고', '비고VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비고'),
('텍스트', '비고', '비고VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비고'),
('텍스트', '비교기호내용', '비교기호내용VC20', 'VARCHAR', 20, NULL, 'N', 'N', NULL, '비교기호내용'),
('번호', '비밀번호', '비밀번호VC50', 'VARCHAR', 50, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비밀번호'),
('번호', '비밀번호', '비밀번호VC512', 'VARCHAR', 512, NULL, 'N', 'N', NULL, '비밀번호'),
('금액', '비용', '비용DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '길이 없는 비용 도메인'),
('금액', '비용', '비용DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비용'),
('비율', '비용편익비율', '비용편익비율DEC6,3', 'NUMERIC', 6, 3, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비용편익비율'),
('비율', '비율', '비율DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비율'),
('비율', '비율', '비율DEC12,9', 'NUMERIC', 12, 9, NULL, NULL, NULL, '어떤 수량의 다른 수량에 대한 비의 값을 정수와 소수로 나타낸 것. 기준량에 대한 비교하는 양의 크기, 즉 (비교하는 양)/(기준양)의 값이다.'),
('비율', '비율', '비율DEC13,9', 'NUMERIC', 13, 9, NULL, NULL, NULL, '어떤 수량의 다른 수량에 대한 비의 값을 정수와 소수로 나타낸 것. 기준량에 대한 비교하는 양의 크기, 즉 (비교하는 양)/(기준양)의 값이다.'),
('비율', '비율', '비율DEC15,4', 'NUMERIC', 15, 4, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비율'),
('비율', '비율', '비율DEC6,3', 'NUMERIC', 6, 3, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비율'),
('수량', '비퇴사량', '비퇴사량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_비퇴사량'),
('비율', '빈도', '빈도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_빈도'),
('텍스트', '사례', '사례VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사례'),
('수량', '사수위', '사수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사수위'),
('금액', '사업비', '사업비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사업비'),
('번호', '사업자등록번호', '사업자등록번호CH10', 'CHAR', 10, NULL, NULL, NULL, NULL, '사업자 등록을 할 때 국세청에서 전산시스템에 따라 자동으로 부여하는 번호'),
('번호', '사업자등록번호', '사업자등록번호VC12', 'VARCHAR', 12, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사업자등록번호'),
('수량', '사용기간', '사용기간DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사용기간'),
('수량', '사용량', '사용량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사용량'),
('수량', '사용량', '사용량DEC18,2', 'NUMERIC', 18, 2, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사용량'),
('금액', '사용료', '사용료DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사용료'),
('분류', '사용목적코드', '사용목적코드VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사용목적코드'),
('분류', '사용자그룹코드', '사용자그룹코드VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사용자그룹코드'),
('번호', '사원번호', '사원번호VC20', 'VARCHAR', 20, NULL, 'N', 'N', NULL, '조달청 사원번호'),
('번호', '사원번호', '사원번호VC8', 'VARCHAR', 8, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사원번호'),
('텍스트', '사유', '사유VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사유'),
('텍스트', '사유', '사유VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사유'),
('텍스트', '사유', '사유VC2000', 'VARCHAR', 2000, NULL, 'N', 'N', NULL, '理由 어떠한 결론이나 결과에 이른 까닭이나 근거.'),
('텍스트', '사유', '사유VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사유'),
('텍스트', '사유', '사유VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사유'),
('분류', '사유코드', '사유코드VC6', 'VARCHAR', 6, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사유코드'),
('수량', '사이즈', '사이즈DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사이즈'),
('텍스트', '사항', '사항VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사항'),
('텍스트', '사항', '사항VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사항'),
('텍스트', '사항', '사항VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_사항'),
('번호', '상세ID', '상세IDVC20', 'VARCHAR', 20, NULL, 'N', 'N', NULL, '상세과제 20자리 도메인'),
('날짜', '상세일시', '상세일시CH20', 'CHAR', 20, NULL, 'N', 'N', NULL, 'TIMESTAMP 데이터를 텍스트로 입력하기 위한 도메인
[yyyyMMddHHmmssSSSSSS]'),
('날짜', '상세일시', '상세일시TMP', 'TIMESTAMP', NULL, NULL, 'N', 'N', NULL, 'PostgreSQL 등에서 DATE 타입으로는 시간값 표현이 되지 않음으로  별도의 TIMESTAMP 도메인을 이용'),
('수량', '상시만수위', '상시만수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_상시만수위'),
('기타', '상한값', '상한값DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_상한값'),
('명', '상호', '상호VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_상호'),
('기타', '상호', '상호VC200', 'VARCHAR', 200, NULL, 'N', 'N', NULL, '상호명  vc200'),
('날짜', '생년월일', '생년월일VC8', 'VARCHAR', 8, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_생년월일'),
('수량', '생산량', '생산량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_생산량'),
('기타', '서명데이터내용', '서명데이터내용BL', 'BLOB', NULL, NULL, 'N', 'N', NULL, '서명데이터내용'),
('금액', '선수금', '선수금DEC15', 'NUMERIC', 15, NULL, 'N', 'N', NULL, '조달고지서 선수금'),
('텍스트', '설명', '설명VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_설명'),
('텍스트', '설명', '설명VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_설명'),
('텍스트', '설명', '설명VC2000', 'VARCHAR', 2000, NULL, 'N', 'N', NULL, '설명'),
('텍스트', '설명', '설명VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_설명'),
('텍스트', '설명', '설명VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_설명'),
('번호', '설비구성항목번호', '설비구성항목번호VC10', 'VARCHAR', 10, NULL, 'N', 'N', NULL, '자산관리시스템에서 관리할 설비의 다양한 업무 영역의 정보를 구성 관리하기 위해 관리하는 항목

항목구성)

I(1) + 일련번호(9)'),
('번호', '설비모듈번호', '설비모듈번호VC4', 'VARCHAR', 4, NULL, 'N', 'N', NULL, '수자원 자산의 설비를 "모듈"로 구분하여 관리하기 위해 부여하는 번호

예시)
M-일련번호(2)'),
('금액', '세액', '세액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_세액'),
('수량', '소계', '소계DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_소계'),
('수량', '소요시간', '소요시간DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_소요시간'),
('주소', '소재지', '소재지VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_소재지'),
('수량', '속도', '속도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_속도'),
('번호', '손괴사고관리번호', '손괴사고관리번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+일련번호(6)'),
('수량', '손실량', '손실량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_손실량'),
('수량', '송전량', '송전량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_송전량'),
('수량', '수', '수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수'),
('수량', '수', '수DEC10', 'NUMERIC', 10, NULL, NULL, NULL, NULL, '셀 수 있는 사물을 세어서 나타낸 값'),
('수량', '수', '수DEC10,3', 'NUMERIC', 10, 3, 'N', 'N', NULL, '재이용유입대장균수
재이용생산대장균수
최대유입대장균수
최소유입대장균수
평균유입대장균수 등의 환경시설에서 사용하는 측정에 대한 수에 사용하는 도메인'),
('수량', '수', '수DEC12,3', 'NUMERIC', 12, 3, 'N', 'N', NULL, '셀 수 있는 사물을 세어서 나타낸 값'),
('수량', '수', '수DEC14', 'NUMERIC', 14, NULL, NULL, NULL, NULL, '셀 수 있는 사물을 세어서 나타낸 값'),
('수량', '수', '수DEC2', 'NUMERIC', 2, NULL, NULL, NULL, NULL, '셀 수 있는 사물을 세어서 나타낸 값'),
('수량', '수', '수DEC3', 'NUMERIC', 3, NULL, NULL, NULL, NULL, '셀 수 있는 사물을 세어서 나타낸 값'),
('수량', '수', '수DEC4,2', 'NUMERIC', 4, 2, NULL, NULL, NULL, '셀 수 있는 사물을 세어서 나타낸 값'),
('수량', '수', '수DEC8,3', 'NUMERIC', 8, 3, NULL, NULL, NULL, '셀 수 있는 사물을 세어서 나타낸 값'),
('기타', '수기등록여부', '수기등록여부CH1', 'CHAR', 1, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수기등록여부'),
('번호', '수도미터번호', '수도미터번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+시퀀스일련번호(6)'),
('금액', '수수료', '수수료DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수수료'),
('금액', '수수료', '수수료DEC15', 'NUMERIC', 15, NULL, 'N', 'N', NULL, '조달고지서 수수료'),
('금액', '수수료', '수수료DEC16,3', 'NUMERIC', 16, 3, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수수료'),
('금액', '수수료', '수수료DEC20,3', 'NUMERIC', 20, 3, 'N', 'N', NULL, '조달청 수수료금액'),
('수량', '수심', '수심DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수심'),
('수량', '수압', '수압DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수압'),
('수량', '수온', '수온DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수온'),
('번호', '수용가번호', '수용가번호VC12', 'VARCHAR', 12, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수용가번호'),
('수량', '수위', '수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수위'),
('비율', '수익률', '수익률DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수익률'),
('수량', '수입량', '수입량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_수입량'),
('금액', '순공사비', '순공사비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_순공사비'),
('차례', '순번', '순번DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_순번'),
('차례', '순서', '순서DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_순서'),
('차례', '순서', '순서DEC10', 'NUMERIC', 10, NULL, NULL, NULL, NULL, '정해진 기준에서 말하는 전후, 좌후, 상하 따위의 차례'),
('차례', '순위', '순위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_순위'),
('수량', '습도', '습도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_습도'),
('날짜', '시', '시VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_시'),
('날짜', '시각', '시각VC6', 'VARCHAR', 6, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_시각'),
('수량', '시간가중평균노출기준값', '시간가중평균노출기준값DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '시간가중평균노출기준값DEC'),
('금액', '시공금액', '시공금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_시공금액'),
('날짜', '시분', '시분VC4', 'VARCHAR', 4, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_시분'),
('번호', '시설작업의뢰내역번호', '시설작업의뢰내역번호VC30', 'VARCHAR', 30, NULL, NULL, NULL, NULL, 'SAP 연계 참조 코드 컬럼'),
('번호', '시스템화면번호', '시스템화면번호DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_시스템화면번호'),
('텍스트', '시행기간', '시행기간VC20', 'VARCHAR', 20, NULL, 'N', 'N', NULL, '시행기간VC20'),
('번호', '시행문서번호', '시행문서번호VC200', 'VARCHAR', 200, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_시행문서번호'),
('번호', '식별번호', '식별번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_식별번호'),
('번호', '식별자', '식별자VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_식별자'),
('번호', '식별자', '식별자VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_식별자'),
('금액', '실적금액', '실적금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_실적금액'),
('수량', '심도', '심도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_심도'),
('비율', '알칼리도', '알칼리도DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '물의 알칼리성의 정도를 아는 척도.'),
('기타', '암호화', '암호화CL', 'CLOB', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_암호화'),
('기타', '암호화', '암호화VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_암호화'),
('기타', '암호화', '암호화VC300', 'VARCHAR', 300, NULL, 'N', 'N', NULL, '暗號化 통신할 내용을 일정한 체계에 따라 암호로 바꿈.'),
('텍스트', '약어', '약어VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_약어'),
('수량', '양정', '양정DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_양정'),
('금액', '여비', '여비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_여비'),
('주소', '연락처', '연락처VC1000', 'VARCHAR', 1000, NULL, 'N', 'N', NULL, '연락기관통보자명 사용'),
('주소', '연락처', '연락처VC200', 'VARCHAR', 200, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_연락처'),
('수량', '연령', '연령DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_연령'),
('텍스트', '연산자내용', '연산자내용VC10', 'VARCHAR', 10, NULL, 'N', 'N', NULL, '연산자내용'),
('수량', '연장', '연장DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_연장'),
('금액', '연체료', '연체료DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_연체료'),
('금액', '연체료', '연체료DEC15', 'NUMERIC', 15, NULL, 'N', 'N', NULL, '조달청연체료'),
('금액', '연체료', '연체료DEC20,3', 'NUMERIC', 20, 3, 'N', 'N', NULL, '조달청 연체료'),
('번호', '연체료상계전표번호', '연체료상계전표번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_연체료상계전표번호'),
('번호', '연체료전표번호', '연체료전표번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_연체료전표번호'),
('비율', '연체율', '연체율DEC6,3', 'NUMERIC', 6, 3, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_연체율'),
('비율', '염분도', '염분도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_염분도'),
('명', '영문명', '영문명VC150', 'VARCHAR', 150, NULL, 'N', 'N', NULL, '영어로 된 이름. VC(150)'),
('명', '영문명', '영문명VC300', 'VARCHAR', 300, NULL, 'N', 'N', NULL, '영문명'),
('명', '영문명', '영문명VC50', 'VARCHAR', 50, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_영문명'),
('날짜', '예보시각', '예보시각VC12', 'VARCHAR', 12, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_예보시각'),
('금액', '예비가격', '예비가격DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_예비가격'),
('금액', '예정가격', '예정가격DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_예정가격'),
('수량', '온도', '온도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_온도'),
('수량', '외경', '외경DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_외경'),
('번호', '외국인등록번호', '외국인등록번호CH13', 'CHAR', 13, NULL, 'N', 'N', NULL, '(7번째 자리) - 1900년대 남(5),여(6) - 2000년대 남(7),여(8)(12번째 자리) - 외국인(9) - 재외국인(8) - 동포(7)'),
('금액', '요금', '요금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_요금'),
('기타', '요금계산여부', '요금계산여부VC1', 'VARCHAR', 1, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_요금계산여부'),
('텍스트', '요약', '요약VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_요약'),
('텍스트', '요약', '요약VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_요약'),
('텍스트', '요약', '요약VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_요약'),
('비율', '요율', '요율DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_요율'),
('텍스트', '용도', '용도VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_용도'),
('텍스트', '용도', '용도VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_용도'),
('텍스트', '용도', '용도VC4000', 'VARCHAR', 4000, NULL, 'N', 'N', NULL, '도메인 설명보완(2022.12.29)_용도'),
('수량', '용량', '용량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_용량'),
('수량', '용수량', '용수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_용수량');

INSERT INTO std_domn_dict (domn_grp_nm, domn_nm, domn_lgc_nm, data_ty, data_len, deci_point, psnl_info_yn, enc_yn, scrbl, dc) VALUES
('금액', '용역금액', '용역금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_용역금액'),
('금액', '용역비', '용역비DEC22', 'NUMERIC', 22, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_용역비'),
('수량', '용존산소량', '용존산소량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_용존산소량'),
('수량', '용존산소량측정값', '용존산소량측정값DEC14,4', 'NUMERIC', 14, 4, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_용존산소량측정값'),
('차례', '우선순위', '우선순위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_우선순위'),
('번호', '우편번호', '우편번호CH5', 'CHAR', 5, NULL, NULL, NULL, NULL, '우편물을 쉽게 분류하기 위하여 과학기술정보통신부에서 지역마다 매긴 번호'),
('번호', '우편번호', '우편번호VC6', 'VARCHAR', 6, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_우편번호'),
('금액', '운영비용', '운영비용DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_운영비용'),
('번호', '운전면허번호', '운전면허번호CH12', 'CHAR', 12, NULL, NULL, NULL, NULL, '차례를 나타내거나 식별하기 위해 붙이는 숫자나 문자를 고정된 길이로 정의한 것'),
('금액', '원가', '원가DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_원가'),
('금액', '원금', '원금DEC15', 'NUMERIC', 15, NULL, 'N', 'N', NULL, '밑천으로 들인 돈이나 이자가 붙지 않은 원래의 돈'),
('텍스트', '원인', '원인VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_원인'),
('텍스트', '원인', '원인VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_원인'),
('날짜', '월', '월VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_월'),
('날짜', '월일', '월일VC4', 'VARCHAR', 4, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_월일'),
('번호', '위도', '위도DEC12,10', 'NUMERIC', 12, 10, NULL, NULL, NULL, '지구 위의 위치를 나타내는 좌표축 중에서 가로로 된 것. 적도를 중심으로 하여 남북으로 평행하게 그은 선'),
('번호', '위도', '위도VC15', 'VARCHAR', 15, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_위도'),
('번호', '위도', '위도VC20', 'VARCHAR', 20, NULL, 'N', 'N', NULL, '좌표상 위도의 값이 기존 도메인 15자리를 초과한 20자 형태로 표현된다.'),
('날짜', '위치시각', '위치시각VC12', 'VARCHAR', 12, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_위치시각'),
('주소', '위치정보', '위치정보VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_위치정보'),
('수량', '유량', '유량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_유량'),
('수량', '유량', '유량DEC20,5', 'NUMERIC', 20, 5, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_유량'),
('수량', '유사량', '유사량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_유사량'),
('분류', '유소견구분코드', '유소견구분코드VC4', 'VARCHAR', 4, NULL, 'N', 'N', NULL, '유소견구분코드'),
('수량', '유속', '유속DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_유속'),
('수량', '유수량', '유수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_유수량'),
('비율', '유수율', '유수율DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_유수율'),
('수량', '유입량', '유입량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_유입량'),
('수량', '유출량', '유출량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_유출량'),
('비율', '율', '율DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_율'),
('비율', '율', '율DEC12,6', 'NUMERIC', 12, 6, NULL, NULL, NULL, '어떤 수량의 다른 수량에 대한 비의 값을 정수와 소수로 나타낸 것'),
('비율', '율', '율DEC20,10', 'NUMERIC', 20, 10, 'N', 'N', NULL, '기존 소수점 자리 부족으로 추가신청'),
('비율', '율', '율DEC20,5', 'NUMERIC', 20, 5, 'N', 'N', NULL, '기존 율이 범위가 작아 추가요청'),
('비율', '율', '율DEC5,2', 'NUMERIC', 5, 2, NULL, NULL, NULL, '어떤 수량의 다른 수량에 대한 비의 값을 정수와 소수로 나타낸 것'),
('비율', '율', '율DEC6,2', 'NUMERIC', 6, 2, NULL, NULL, NULL, '어떤 수량의 다른 수량에 대한 비의 값을 정수와 소수로 나타낸 것'),
('비율', '율', '율DEC6,3', 'NUMERIC', 6, 3, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_율'),
('비율', '율', '율DEC7,2', 'NUMERIC', 7, 2, NULL, NULL, NULL, '어떤 수량의 다른 수량에 대한 비의 값을 정수와 소수로 나타낸 것'),
('텍스트', '이력', '이력VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_이력'),
('주소', '이메일', '이메일VC100', 'VARCHAR', 100, NULL, 'N', 'N', NULL, '이메일 주소'),
('기타', '이메일', '이메일VC200', 'VARCHAR', 200, NULL, 'N', 'N', NULL, '이메일 도메인 VC200'),
('주소', '이메일', '이메일VC50', 'VARCHAR', 50, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_이메일'),
('분류', '이메일상태구분코드', '이메일상태구분코드VC2', 'VARCHAR', 2, NULL, 'N', 'N', NULL, '이메일상태구분코드'),
('금액', '이자소득세', '이자소득세DEC15', 'NUMERIC', 15, NULL, 'N', 'N', NULL, '이자소득에 대한 세금'),
('기타', '이전시설구분코드', '이전시설구분코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '개별코드 신청'),
('번호', '인허가신청관리번호', '인허가신청관리번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+일련번호(6)'),
('날짜', '일', '일DEC10', 'NUMERIC', 10, NULL, 'N', 'N', NULL, 'UNIXTIMESTAMP값'),
('날짜', '일', '일VC10', 'VARCHAR', 10, NULL, 'N', 'N', NULL, '10자리 일자'),
('날짜', '일', '일VC14', 'VARCHAR', 14, NULL, 'N', 'N', NULL, '14자리 날짜도메인'),
('기타', '일', '일VC20', 'VARCHAR', 20, NULL, 'N', 'N', NULL, '조달청 차세대 나라장터 연계 전자문서 중 대금고지서 개찰일시 항목'),
('날짜', '일', '일VC8', 'VARCHAR', 8, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_일'),
('금액', '일반관리비', '일반관리비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_일반관리비'),
('금액', '일반재난감면액', '일반재난감면액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_일반재난감면액'),
('수량', '일수', '일수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_일수'),
('날짜', '일시', '일시CH8', 'CHAR', 8, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_일시'),
('날짜', '일시', '일시DT', 'DATE', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_일시'),
('날짜', '일자', '일자VC2', 'VARCHAR', 2, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_일자'),
('수량', '입경', '입경DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_입경'),
('수량', '입고량', '입고량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_입고량'),
('번호', '입고처리번호', '입고처리번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+시퀀스일련번호(6)'),
('수량', '입도', '입도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_입도'),
('번호', '자동차등록번호', '자동차등록번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, '국토교통부장관이 고시한 기준에 따라 자동차의 종류와 용도별로 구분하여 자동차 마다에 매긴 번호'),
('수량', '자릿수', '자릿수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_자릿수'),
('수량', '자체기동값', '자체기동값DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_자체기동값'),
('번호', '작업의뢰내역번호', '작업의뢰내역번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+일련번호(6)'),
('수량', '잔량', '잔량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_잔량'),
('금액', '잔액', '잔액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_잔액'),
('비율', '장폭비', '장폭비DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_장폭비'),
('금액', '재료비', '재료비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_재료비'),
('수량', '저수량', '저수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_저수량'),
('수량', '저수위', '저수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_저수위'),
('비율', '적용률', '적용률DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_적용률'),
('비율', '적용률', '적용률DEC6,3', 'NUMERIC', 6, 3, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_적용률'),
('날짜', '전기일', '전기일VC8', 'VARCHAR', 8, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_전기일'),
('비율', '전기전도도', '전기전도도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_전기전도도'),
('비율', '전기전도도', '전기전도도DEC10,3', 'NUMERIC', 10, 3, 'N', 'N', NULL, '최대재이용유입전기전도도
최소재이용유입전기전도도
평균재이용유입전기전도도
최대재이용생산전기전도도
최소재이용생산전기전도도
평균재이용생산전기전도도 등의 환경시설에서 사용하는 측정 전기전도도에 사용하는 도메인'),
('수량', '전력량', '전력량DEC18,2', 'NUMERIC', 18, 2, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_전력량'),
('비율', '전수비', '전수비DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_전수비'),
('수량', '전압', '전압DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_전압'),
('번호', '전자수용가번호', '전자수용가번호VC15', 'VARCHAR', 15, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_전자수용가번호'),
('기타', '전체선수금처리여부', '전체선수금처리여부CH1', 'CHAR', 1, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_전체선수금처리여부'),
('번호', '전표관리번호', '전표관리번호VC11', 'VARCHAR', 11, NULL, NULL, NULL, NULL, 'YYYY(4)+일련번호(7)'),
('번호', '전화번호', '전화번호VC100', 'VARCHAR', 100, NULL, 'N', 'N', NULL, '환경산업기술원에서 사용하는 전화번호'),
('번호', '전화번호', '전화번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_전화번호'),
('번호', '전화번호', '전화번호VC30', 'VARCHAR', 30, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_전화번호'),
('수량', '점수', '점수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_점수'),
('수량', '점수', '점수DEC10,3', 'NUMERIC', 10, 3, 'N', 'N', NULL, '點數 성적을 나타내는 숫자'),
('수량', '정량', '정량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_정량'),
('텍스트', '정보', '정보VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_정보'),
('텍스트', '정보', '정보VC1000', 'VARCHAR', 1000, NULL, 'N', 'N', NULL, '情報. 관찰이나 측정을 통하여 수집한 자료를 실제 문제에 도움이 될 수 있도록 정리한 지식. 또는 그 자료.'),
('텍스트', '정보', '정보VC40', 'VARCHAR', 40, NULL, 'N', 'N', NULL, '길이 40 정보 도메인'),
('텍스트', '정보', '정보VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_정보'),
('텍스트', '정보', '정보VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_정보'),
('번호', '정산기본내용번호', '정산기본내용번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, '일련번호(10)'),
('금액', '정산액', '정산액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_정산액'),
('금액', '정산잔액', '정산잔액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_정산잔액'),
('수량', '정수', '정수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_정수'),
('텍스트', '정의', '정의VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_정의'),
('텍스트', '제목', '제목VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_제목'),
('텍스트', '제목', '제목VC500', 'VARCHAR', 500, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_제목'),
('금액', '조사비', '조사비DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_조사비'),
('금액', '조정금액', '조정금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_조정금액'),
('수량', '조정량', '조정량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_조정량'),
('수량', '조회수', '조회수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_조회수'),
('명', '종류명', '종류명VC100', 'VARCHAR', 100, NULL, 'N', 'N', NULL, '어떤 기준에 따라 나눈 갈래의 명칭.'),
('명', '종류명', '종류명VC50', 'VARCHAR', 50, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_종류명'),
('번호', '좌표', '좌표DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_좌표'),
('번호', '좌표', '좌표DEC13,10', 'NUMERIC', 13, 10, NULL, NULL, NULL, '평면이나 공간 안의 임의의 점의 위치를 나타내는 수나 수의 짝'),
('주소', '주소', '주소VC15', 'VARCHAR', 15, NULL, NULL, NULL, NULL, '사람이 살고 있는 곳이나 기관, 회사 따위가 자리 잡고 있는 곳을 행정 구역으로 나타낸 이름 또는, 데이터가 저장되어 있는 기억 장소의 위치. 또는 그것을 나타내는 수. 바이트(byte)를 단위로 부여'),
('주소', '주소', '주소VC17', 'VARCHAR', 17, NULL, NULL, NULL, NULL, '사람이 살고 있는 곳이나 기관, 회사 따위가 자리 잡고 있는 곳을 행정 구역으로 나타낸 이름 또는, 데이터가 저장되어 있는 기억 장소의 위치. 또는 그것을 나타내는 수. 바이트(byte)를 단위로 부여'),
('주소', '주소', '주소VC200', 'VARCHAR', 200, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_주소'),
('주소', '주소', '주소VC2000', 'VARCHAR', 2000, NULL, NULL, NULL, NULL, '사람이 살고 있는 곳이나 기관, 회사 따위가 자리 잡고 있는 곳을 행정 구역으로 나타낸 이름 또는, 데이터가 저장되어 있는 기억 장소의 위치. 또는 그것을 나타내는 수. 바이트(byte)를 단위로 부여'),
('주소', '주소', '주소VC320', 'VARCHAR', 320, NULL, NULL, NULL, NULL, '사람이 살고 있는 곳이나 기관, 회사 따위가 자리 잡고 있는 곳을 행정 구역으로 나타낸 이름 또는, 데이터가 저장되어 있는 기억 장소의 위치. 또는 그것을 나타내는 수. 바이트(byte)를 단위로 부여'),
('텍스트', '주의사항', '주의사항VC1000', 'VARCHAR', 1000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_주의사항'),
('텍스트', '주의사항', '주의사항VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_주의사항'),
('수량', '주파수', '주파수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_주파수'),
('번호', '준공관리번호', '준공관리번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, '일련번호(10)'),
('금액', '준공금액', '준공금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_준공금액'),
('금액', '중가산금', '중가산금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_중가산금'),
('금액', '지급액', '지급액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_지급액'),
('번호', '지방급수공사번호', '지방급수공사번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+시퀀스일련번호(6)'),
('번호', '지방긴급복구번호', '지방긴급복구번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+일련번호(6)'),
('주소', '지번', '지번VC20', 'VARCHAR', 20, NULL, 'N', 'N', NULL, '지번주소에 한글명을 들어 있음. 예시)산3-343'),
('주소', '지번', '지번VC4', 'VARCHAR', 4, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_지번'),
('주소', '지번', '지번VC8', 'VARCHAR', 8, NULL, 'N', 'N', NULL, '분양정보시스템에서 사용되는 잔지 지번이 본번 + 부번 으로 구성되어 있어서 8자리 길이 도메인이 필요함'),
('주소', '지번', '지번VC9', 'VARCHAR', 9, NULL, 'N', 'N', NULL, '분양정보시스템에서 사용되어지는 지번이 필지구분+본번+부번 으로 구성되어 있어서 9자리 길이 도메인이 필요함'),
('수량', '지수', '지수DEC3', 'NUMERIC', 3, NULL, 'N', 'N', NULL, '물가나 임금 따위의 변동을 알기 쉽게 나타내기 위하여 일정한 때를 100으로 기준하여 비교하는 숫자'),
('수량', '지수', '지수DEC5,3', 'NUMERIC', 5, 3, 'N', 'N', NULL, '기술성 평가 점수(0~10점, 소수점3자리)'),
('금액', '지체상금', '지체상금DEC15', 'NUMERIC', 15, NULL, 'N', 'N', NULL, '조달고지서 지체상금'),
('번호', '지형지물관리번호', '지형지물관리번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+일련번호(6)'),
('번호', '차대번호', '차대번호CH17', 'CHAR', 17, NULL, NULL, NULL, NULL, '차량의 도난을 방지하고 차량 결함을 파악하기 위해서 자동차의 보닛 안에 적어 놓은 자동차의 개별 번호'),
('수량', '차수', '차수DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '차수(差數) [명사] 차가 생긴 수.

용어 예시) 감정평가차수 NUMERIC'),
('금액', '차액', '차액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_차액'),
('수량', '처리기간', '처리기간DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_처리기간'),
('수량', '처리량', '처리량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_처리량'),
('수량', '처리량', '처리량DEC10,3', 'NUMERIC', 10, 3, 'N', 'N', NULL, '탈수 슬러지 처리량
협잡물 처리량
액상 슬러지 처리량
탈수 슬러지 처리량
협잡물 처리량
액상 슬러지 처리량 등의 환경시설에서 사용하는 처리량에 사용하는 도메인'),
('수량', '체적', '체적DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_체적'),
('수량', '초과량', '초과량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_초과량'),
('수량', '총건수', '총건수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_총건수'),
('금액', '총공사비', '총공사비DEC22', 'NUMERIC', 22, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_총공사비'),
('수량', '총량', '총량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_총량'),
('수량', '총면적', '총면적DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_총면적'),
('금액', '총액', '총액DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '길이 없는 총액 도메인'),
('금액', '총액', '총액DEC22', 'NUMERIC', 22, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_총액'),
('수량', '총용존고형량', '총용존고형량DEC18,2', 'NUMERIC', 18, 2, 'N', 'N', NULL, '물이 처리된 유기 물질, 무기염 또는 화학 물질을 포함하여 물 속에 있는 많은 것들을 결합한 측정값이다.'),
('수량', '총인측정값', '총인측정값DEC14,4', 'NUMERIC', 14, 4, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_총인측정값'),
('수량', '최고수위', '최고수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_최고수위'),
('수량', '최대발전용량', '최대발전용량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_최대발전용량'),
('수량', '최대수위', '최대수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_최대수위'),
('수량', '최대치', '최대치DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_최대치'),
('수량', '최소치', '최소치DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_최소치'),
('수량', '최저수위', '최저수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_최저수위'),
('금액', '추정가격', '추정가격DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_추정가격'),
('금액', '추정금액', '추정금액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_추정금액'),
('비율', '출석율', '출석율DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '출석률DEC'),
('금액', '충당금', '충당금DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_충당금'),
('수량', '취수량', '취수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_취수량'),
('기타', '취수지점수원코드', '취수지점수원코드VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '(개별코드 신청)
취수지점과 연결된 수원을 식별하기 위한 고유 코드'),
('번호', '측량성과번호', '측량성과번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+일련번호(6)'),
('수량', '측선수', '측선수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_측선수'),
('텍스트', '카카오알림톡템플릿코드', '카카오알림톡템플릿코드VC20', 'VARCHAR', 20, NULL, 'N', 'N', NULL, '카카오알림톡 템플릿 코드'),
('번호', '컬럼번호', '컬럼번호DEC20', 'NUMERIC', 20, NULL, 'N', 'N', NULL, '열번호'),
('수량', '클로로필A측정값', '클로로필A측정값DEC14,4', 'NUMERIC', 14, 4, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_클로로필A측정값'),
('수량', '킬로미터', '킬로미터DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_킬로미터'),
('비율', '탁도', '탁도DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_탁도'),
('비율', '탁도', '탁도DEC10,3', 'NUMERIC', 10, 3, 'N', 'N', NULL, '최대재이용유입탁도
최소재이용유입탁도
평균재이용유입탁도
최대재이용생산탁도
최소재이용생산탁도
평균재이용생산탁도 등의 환경시설에서 사용하는 측정 탁도에 사용하는 도메인'),
('수량', '토양수분량', '토양수분량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_토양수분량'),
('수량', '톤수', '톤수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_톤수'),
('수량', '퇴사량', '퇴사량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_퇴사량'),
('수량', '투입량', '투입량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_투입량'),
('금액', '특별재난감면액', '특별재난감면액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_특별재난감면액'),
('텍스트', '특이사항', '특이사항VC4000', 'VARCHAR', 4000, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_특이사항'),
('텍스트', '파라미터', '파라미터VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_파라미터'),
('텍스트', '파라미터', '파라미터VC500', 'VARCHAR', 500, NULL, 'N', 'N', NULL, '파라미터 V500'),
('주소', '파일경로', '파일경로VC255', 'VARCHAR', 255, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_파일경로'),
('주소', '파일경로', '파일경로VC500', 'VARCHAR', 500, NULL, 'N', 'N', NULL, '컴퓨터 명령의 논리 계열, 즉 루틴을 수행할 때 컴퓨터가 취하는 논리적 과정이나 방향 행로'),
('수량', '판매량', '판매량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_판매량'),
('번호', '팩스번호', '팩스번호VC100', 'VARCHAR', 100, NULL, 'N', 'N', NULL, '환경산업기술원에서 사용하는 팩스번호'),
('번호', '팩스번호', '팩스번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_팩스번호'),
('번호', '팩스번호', '팩스번호VC30', 'VARCHAR', 30, NULL, 'N', 'N', NULL, '조달청 팩스번호'),
('수량', '펌프양정', '펌프양정DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_펌프양정'),
('수량', '편각', '편각DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_편각'),
('수량', '평', '평DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_평'),
('금액', '평가액', '평가액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_평가액'),
('금액', '평가액', '평가액DEC15', 'NUMERIC', 15, NULL, 'N', 'N', NULL, '조달청 업체주력분야 데이터의 업체 시공능력평가액 정보'),
('수량', '평가점수', '평가점수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_평가점수'),
('수량', '평가점수', '평가점수DEC2,1', 'NUMERIC', 2, 1, 'N', 'N', NULL, '1점 만점 평가점수'),
('수량', '평가점수', '평가점수DEC6,3', 'NUMERIC', 6, 3, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_평가점수'),
('분류', '평가코드', '평가코드VC6', 'VARCHAR', 6, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_평가코드'),
('수량', '평수량', '평수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_평수량'),
('수량', '평수위', '평수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_평수위'),
('수량', '표고', '표고DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_표고'),
('수량', '풍속', '풍속DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_풍속'),
('수량', '풍수량', '풍수량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_풍수량'),
('수량', '풍수위', '풍수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_풍수위'),
('수량', '필요량', '필요량DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_필요량'),
('기타', '하한값', '하한값DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_하한값'),
('명', '학명', '학명VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_학명'),
('명', '한글명', '한글명VC100', 'VARCHAR', 100, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_한글명'),
('명', '한글명', '한글명VC300', 'VARCHAR', 300, NULL, 'N', 'N', NULL, '한글로 된 이름. VC300'),
('비율', '할인율', '할인율DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_할인율');

INSERT INTO std_domn_dict (domn_grp_nm, domn_nm, domn_lgc_nm, data_ty, data_len, deci_point, psnl_info_yn, enc_yn, scrbl, dc) VALUES
('비율', '함수율', '함수율DEC6,3', 'NUMERIC', 6, 3, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_함수율'),
('수량', '합계', '합계DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_합계'),
('번호', '협력업체번호', '협력업체번호VC4', 'VARCHAR', 4, NULL, NULL, NULL, NULL, '일련번호(4)'),
('번호', '협력업체지정계획관리번호', '협력업체지정계획관리번호VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, 'YYYY(4)+일련번호(6)'),
('수량', '홍수기제한수위', '홍수기제한수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_홍수기제한수위'),
('수량', '홍수위', '홍수위DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_홍수위'),
('텍스트', '화면XML', '화면XMLVC500', 'VARCHAR', 500, NULL, 'N', 'N', NULL, '웹스퀘어로 작성된 화면 XML 정의값'),
('명', '확장자명', '확장자명VC10', 'VARCHAR', 10, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_확장자명'),
('금액', '환불액', '환불액DEC13', 'NUMERIC', 13, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_환불액'),
('수량', '환율', '환율DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_환율'),
('번호', '회사전화번호', '회사전화번호VC11', 'VARCHAR', 11, NULL, 'N', 'N', NULL, '가입된 전화마다 매겨져 있는 일정한 번호(지역번호(2~3자리)+앞자리전화번호(3~4자리)+뒷자리전화번호(4자리)or(인터넷전화번호(3자리)+앞자리전화번호(3~4자리)+뒷자리전화번호(4자리)or(전국대표번호(4자리)+뒷자리전화번호(4자리)or(이동통신번호(3자리)+앞자리전화번호(3~4자리)+뒷자리전화번호(4자리)'),
('수량', '회차', '회차DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_회차'),
('수량', '횟수', '횟수DEC', 'NUMERIC', NULL, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_횟수'),
('번호', '휴대폰번호', '휴대폰번호VC20', 'VARCHAR', 20, NULL, NULL, NULL, NULL, '도메인 설명보완(2022.11.29)_휴대폰번호'),
('수량', '휴무시간', '휴무시간DEC', 'NUMERIC', NULL, NULL, 'N', 'N', NULL, '직무를 보지 않고 하루 또는 한동안 쉰 시간 값');

-- 총 615건 입력 완료
